import { Validators } from '@angular/forms';

export const searchExample =
{
    "draw": 0,
    "recordsFiltered": 115,
    "recordsTotal": 115,
    "data": [
        {
            "id": 81680,
            "nomeCrianca": "ADRYAN NASCIMENTO BARBOSA DE SOUZA",
            "nomePai": "ALEX SANDRO BARBOSA DE SOUZA",
            "nomeMae": "GISLAINE OLIVEIRA DO NASCIMENTO",
            "oAvoPaterno": "JOSÉ FRANCISCO DE JESUS SOUZA",
            "aAvoPaterna": "LUZIA BARBOSA",
            "oAvoMaterno": "ADEMIR ALENCAR DO NASCIMENTO",
            "aAvoMaterna": "DALVA DE OLIVEIRA NASCIMENTO",
            "livro": "0198",
            "termo": "000121057 ",
            "folha": "232V",
            "dataNascimento": "05/11/2004",
            "dataRegistro": "09/11/2004"
        },
        {
            "id": 252802,
            "nomeCrianca": "ÁGATHA DO PRADO RUSSO",
            "nomePai": "ALEX SANDRO RUSSO DA SILVA",
            "nomeMae": "ANA CLAUDIA DE SOUZA DO PRADO",
            "oAvoPaterno": "LAURENTINO JOSE DA SILVA",
            "aAvoPaterna": "MARTA JENATE RUSSO DA SILVA",
            "oAvoMaterno": "EDINO LUIZ DO PRADO",
            "aAvoMaterna": "DIMARI DE SOUZA DO PRADO",
            "livro": "0254",
            "termo": "000153907 ",
            "folha": "112V",
            "dataNascimento": "03/12/2012",
            "dataRegistro": "10/12/2012"
        },
        {
            "id": 59210,
            "nomeCrianca": "ALESSANDRO DOS SANTOS LISBOA",
            "nomePai": "ALEX SANDRO LISBOA CANUTO",
            "nomeMae": "SUHELY DOS SANTOS NOGUEIRA",
            "oAvoPaterno": "MANOEL BEZERRA CANUTO",
            "aAvoPaterna": "MARIA HEDILA LISBOA CANUTO",
            "oAvoMaterno": "JARBAS CARDOSO NOGUEIRA",
            "aAvoMaterna": "SILVANIA PEREIRA DOS SANTOS",
            "livro": "0184",
            "termo": "000112611 ",
            "folha": "154V",
            "dataNascimento": "18/08/2002",
            "dataRegistro": "06/09/2002"
        },
        {
            "id": 112219,
            "nomeCrianca": "ALEXANDRE DA SILVA SANTOS",
            "nomePai": "ALEX SANDRO JERONIMO SANTOS",
            "nomeMae": "CECILIA FRANCISCA DA SILVA",
            "oAvoPaterno": "NEIVALDO LARANJEIRA SANTOS",
            "aAvoPaterna": "MARLENE JERONIMO SANTOS",
            "oAvoMaterno": " ",
            "aAvoMaterna": "MARIA JOSE SILVA",
            "livro": "0250",
            "termo": "000151583 ",
            "folha": "126 ",
            "dataNascimento": "15/03/2012",
            "dataRegistro": "27/03/2012"
        },
        {
            "id": 113683,
            "nomeCrianca": "ALEXIA CASTRO DAMACENO DOS SANTOS",
            "nomePai": "ALEX SANDRO DAMACENO DOS SANTOS",
            "nomeMae": "ADELITA APARECIDA DA SILVA CASTRO",
            "oAvoPaterno": "RONALDO PACHECO DOS SANTOS",
            "aAvoPaterna": "SORAIA DAMACENO",
            "oAvoMaterno": "PAULO ROBERTO DA SILVA CASTRO",
            "aAvoMaterna": "ANA MARIA DA CONCEIÇÃO DA SILVA CASTRO",
            "livro": "0252",
            "termo": "000153046 ",
            "folha": "276 ",
            "dataNascimento": "29/08/2012",
            "dataRegistro": "31/08/2012"
        },
        {
            "id": 51057,
            "nomeCrianca": "ALEX SANDRO BISERRA DE SÁ",
            "nomePai": "ERASMO ALEX CANDIDO DE SÁ",
            "nomeMae": "FABIANA BISERRA",
            "oAvoPaterno": "ADAMY CANDIDO DE SÁ",
            "aAvoPaterna": "REGINA CANDIDO DE SÁ",
            "oAvoMaterno": "JOSÉ VITORIANO BISERRA",
            "aAvoMaterna": "MARIA APARECIDA BISERRA",
            "livro": "0170",
            "termo": "000104454 ",
            "folha": "185 ",
            "dataNascimento": "20/06/2000",
            "dataRegistro": "03/07/2000"
        },
        {
            "id": 104111,
            "nomeCrianca": "ALEX SANDRO FRANCISCO DE SOUZA",
            "nomePai": "ADSON BISPO DE SOUZA",
            "nomeMae": "ANGELA DO AMARAL FRANCISCO",
            "oAvoPaterno": "ADAILTON RAMOS DE SOUZA",
            "aAvoPaterna": "MARIA LUIZA BISPO DE SOUZA",
            "oAvoMaterno": " ",
            "aAvoMaterna": "MARINALVA ROSANGELA FRANCISCO",
            "livro": "0236",
            "termo": "000143471 ",
            "folha": "208V",
            "dataNascimento": "27/01/2010",
            "dataRegistro": "29/01/2010"
        },
        {
            "id": 56175,
            "nomeCrianca": "ALEX SANDRO RODRIGUES MARQUES",
            "nomePai": "JILSON AZEVEDO MARQUES",
            "nomeMae": "RENATA DOS SANTOS RODRIGUES",
            "oAvoPaterno": "JOAQUIM AZEVEDO MARQUES",
            "aAvoPaterna": "MARILENE ALVES AZEVEDO",
            "oAvoMaterno": "JOÃO CLAUDIO PINA RODRIGUES",
            "aAvoMaterna": "NEUZA MARIA DOS SANTOS RODRIGUES",
            "livro": "0179",
            "termo": "000109573 ",
            "folha": "126 ",
            "dataNascimento": "09/10/2001",
            "dataRegistro": "19/10/2001"
        },
        {
            "id": 263871,
            "nomeCrianca": "ALICE VITORIA OLIVEIRA SOARES",
            "nomePai": "ALEX SANDRO SOARES DA SILVA",
            "nomeMae": "LUANA OLIVEIRA DA SILVA",
            "oAvoPaterno": "JOSE LAETE SOARES DA SILVA",
            "aAvoPaterna": "LUCEMAR MARIA DA SILVA",
            "oAvoMaterno": "AGRIPINO DA SILVA",
            "aAvoMaterna": "ANA LUCIA DE OLIVEIRA",
            "livro": "0263",
            "termo": "000159113 ",
            "folha": "059 ",
            "dataNascimento": "07/06/2014",
            "dataRegistro": "24/06/2014"
        },
        {
            "id": 256626,
            "nomeCrianca": "ALICIA BARBOSA DE SOUZA",
            "nomePai": "ALEX SANDRO DE SOUZA, NATURAL DE ITAPEVA - SP",
            "nomeMae": "MARIA BARBOSA DOS SANTOS, NATURAL DE SÃO PAULO - SP",
            "oAvoPaterno": "",
            "aAvoPaterna": "MARINA DE SOUZA",
            "oAvoMaterno": "JOAQUIM SEBASTIÃO DOS SANTOS",
            "aAvoMaterna": "ALCINA BARBOSA DOS SANTOS",
            "livro": "0258",
            "termo": "000156226 ",
            "folha": "090 ",
            "dataNascimento": "29/07/2013",
            "dataRegistro": "05/08/2013"
        }
    ]
};